version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: swagger-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: swagger-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678